.pragma library

var MARGIN_DEFAULT = 0;
var MARGIN_XLARGE = 16;
var SMALL_IMAGE_MAX_WIDTH = 240;
var SMALL_IMAGE_MAX_HEIGHT = SMALL_IMAGE_MAX_WIDTH;

var DETAILS_TOP_MARGIN_LANDSCAPE = 40;
var DETAILS_TOP_MARGIN_PORTRAIT = MARGIN_XLARGE;
var DETAILS_SPACING = 10;

var DETAILTEXT_COLOR = "white";

var COMMENTSLIST_TOP_MARGIN = 10
var PROGRESSBAR_LABEL_BOTTOM_MARGIN = 4;
var PROGRESSBAR_LABEL_COLOR = "white";

var SLIDER_BOTTOM_MARGIN = 65;
var SLIDER_SIDE_MARGIN = 25;
var SLIDER_OPACITY = 1;

// Flickr serves thumbnails that are 79x79, having a larger
// THUMBNAIL_SIDE may result in bad thumbnail quality
var THUMBNAIL_SIDE = 97;
var THUMBNAIL_BORDER_WIDTH = 1;
var THUMBNAIL_SPACING = 6;
var THUMBNAIL_WRAPPER_SIDE = THUMBNAIL_SIDE + THUMBNAIL_BORDER_WIDTH * 2;
var THUMBNAIL_WRAPPER_COLOR = "black"

var FLICKRPAGE_BG_COLOR = "#343434";
var FLICKRPAGE_BG_OPACITY = 0.3;

var LARGEIMAGE_ERROR_MSG_COLOR = "white";

var LISTDELEGATE_SPACING = 2;
var LISTDELEGATE_MARGIN = 10;
var LISTDELEGATE_TITLE_COLOR = "white";
var LISTDELEGATE_TEXT_COLOR = "#cccccc";
var LISTDELEGATE_STYLE_COLOR = "black";

var GRIDVIEW_MARGIN = 5;

var LISTVIEW_MARGIN = 5;
var LISTVIEW_SPACING = 10;

var SEARCHBAR_HEIGHT = 60;
var SEARCHBAR_FONT = 12;
var SEARCHBAR_FONT_PIXELSIZE = SEARCHBAR_HEIGHT - 30;
var SEARCHBAR_MARGIN = 10;
var SEARCHBAR_BORDER_COLOR = "#b0b0b0";
var SEARCHBAR_BORDER_WIDTH = 3;
var SEARCHBAR_RADIUS = 5;
